#!/usr/bin/php
<?php
require_once __DIR__. '/vendor/autoload.php';

$faker = Faker\Factory::create();
echo "CSV converter , made by Grey\n";

for ($i=0; $i < 10; $i++) {
    echo $faker->name, "\n";
}